import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import FixedGearbikes from "../components/FixedGearbikes";
import Aboutcontact from "../components/Aboutcontact";

export default function fixedgearbikes() {
  return (
    <div>
      <Head>
        <title>Lizwheels | FixedGear Bikes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Navbar />
      <Hero />
      <FixedGearbikes />
      <Aboutcontact />
    </div>
  );
}
