import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Mountainbikes from "../components/mountainbikes";
import Aboutcontact from "../components/Aboutcontact";

export default function mountainbikes() {
  return (
    <div>
      <Head>
        <title>Lizwheels | Mountain Bikes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Navbar />
      <Hero />
      <Mountainbikes />
      <Aboutcontact />
    </div>
  );
}
